### ISSUE TITLE
"Buf" QUserType...?

### ISSUE THREAD

**Issue by Zren** [Zren/PyQuassel#6]
allejo on IRC had this traceback.

```
Traceback (most recent call last):
  File "quasselbot.py", line 74, in <module>
    quasselClient.run()
  File "/home/allejo/PyQuassel/quasselclient.py", line 269, in run
    self.createSession()
  File "/home/allejo/PyQuassel/quasselclient.py", line 262, in createSession
    self.readSessionState()
  File "/home/allejo/PyQuassel/quasselclient.py", line 114, in readSessionState
    data = self.stream.read()
  File "/home/allejo/PyQuassel/qt.py", line 315, in read
    obj = self.readQVariant()
  File "/home/allejo/PyQuassel/qt.py", line 337, in readQVariant
    val = self.readQMap()
  File "/home/allejo/PyQuassel/qt.py", line 388, in readQMap
    value = self.readQVariant()
  File "/home/allejo/PyQuassel/qt.py", line 337, in readQVariant
    val = self.readQMap()
  File "/home/allejo/PyQuassel/qt.py", line 388, in readQMap
    value = self.readQVariant()
  File "/home/allejo/PyQuassel/qt.py", line 350, in readQVariant
    val = self.readQList()
  File "/home/allejo/PyQuassel/qt.py", line 468, in readQList
    val = self.readQVariant()
  File "/home/allejo/PyQuassel/qt.py", line 370, in readQVariant
    raise Exception("QUserType.name", name)
Exception: ('QUserType.name', 'Buf')
```

**Comment by EcmaXp** [comment]
Maybe #8 pull request fix this problem.
